# docker-compose.yml
version: '3.8'

services:
  command:
    build: .
    command: python edbot_command.py
    env_file: .env
    volumes:
      - /container-data/edbot/data:/app/data
      - /container-data/edbot/logs:/app/logs 
    restart: unless-stopped

  listener:
    build: .
    command: python edbot_listener.py
    env_file: .env
    volumes:
      - /container-data/edbot/data:/app/data
      - /container-data/edbot/logs:/app/logs  
    restart: unless-stopped

volumes:
  edbot-data:
